name: Commit Stage
on: push

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up Jdk
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: 코드 취약성 스캔
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "#{{github.workspace}}"
          fail-build: false
          severity-cutoff: high
          acs-report-enable: true
      - name: 업로드 취약성 리포트
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
          category: my-analysis-tool
      - name: 빌드, unit tests and 통합 테스트
        run: |
          chmod +x gradlew
          ./gradlew build

